from config import SYMBOLS
from history import get_history
from analysis.timeframe import analyze_timeframes, final_decision
from telegram import send_message
from notify import send_notification
from logger import logger

last_alerts = {}


def market_scan():

    logger.info("========== NAKSHATRA AI Scan Started ==========")

    for symbol in SYMBOLS:

        try:

            results = analyze_timeframes(symbol)

            decision = final_decision(results)

            signal = decision["signal"]
            score = decision["score"]

            if signal == "WAIT":
                logger.info(f"{symbol}: WAIT")
                continue

            previous = last_alerts.get(symbol)

            if previous == signal:
                logger.info(f"{symbol}: Duplicate Alert Skipped")
                continue

            last_alerts[symbol] = signal

            price = "-"

            try:
                df = get_history(symbol)

                if not df.empty:
                    price = round(float(df["close"].iloc[-1]), 2)

            except Exception as e:
                logger.error(f"{symbol}: Price Fetch Error: {e}")

            tf5 = results.get("5m", {})
            tf15 = results.get("15m", {})
            tf1h = results.get("1h", {})
            tf4h = results.get("4h", {})

            message = f"""
🚀 NAKSHATRA AI

📊 Symbol : {symbol}

💰 Price : {price}

🎯 Signal : {signal}

⭐ Score : {score}

-------------------------

5m : {tf5.get("signal","-")}
15m : {tf15.get("signal","-")}
1h : {tf1h.get("signal","-")}
4h : {tf4h.get("signal","-")}

-------------------------

Generated by NAKSHATRA AI
"""

            telegram_ok = send_message(message)

            if telegram_ok:
                logger.info(f"{symbol}: Telegram Sent")
            else:
                logger.warning(f"{symbol}: Telegram Failed")

            notify_ok = send_notification(
                title=f"{symbol} {signal}",
                message=message
            )

            if notify_ok:
                logger.info(f"{symbol}: ntfy Sent")
            else:
                logger.warning(f"{symbol}: ntfy Failed")

        except Exception as e:

            logger.exception(f"{symbol}: {e}")

    logger.info("========== Scan Finished ==========")
